name: Accelerate integration tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  accelerate:
    name: Test Accelerate integration
    runs-on: [self-hosted, linux, x64, gaudi2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull image
        run: |
          docker pull vault.habana.ai/gaudi-docker/1.19.0/ubuntu22.04/habanalabs/pytorch-installer-2.5.1:latest
      - name: Run tests
        run: |
          docker run \
          --rm \
          --shm-size=64g \
          --runtime=habana \
          --cap-add=sys_nice \
          -v $PWD:/root/workspace \
          --workdir=/root/workspace \
          -e OMPI_MCA_btl_vader_single_copy_mechanism=none \
          -e HABANA_VISIBLE_DEVICES=$DOCKER_HABANA_VISIBLE_DEVICES \
          vault.habana.ai/gaudi-docker/1.19.0/ubuntu22.04/habanalabs/pytorch-installer-2.5.1:latest \
          /bin/bash tests/ci/accelerate.sh
