name: Accelerate integration tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  accelerate:
    name: Test Accelerate integration
    runs-on: [self-hosted, linux, x64, gaudi2]

    steps:
      # stop all running containers
      - name: sanitize runner
        run: |
          docker ps -q | xargs docker stop